platform :ios, "8.0"

pod "React",
  path: "../node_modules/react-native",
  subspecs: %w{
    Core
    RCTAnimation
    RCTImage
    RCTText
    RCTNetwork
    RCTWebSocket
  }
pod "Yoga", path: "../node_modules/react-native/ReactCommon/yoga"
pod "react-native-branch", path: "../node_modules/react-native-branch"
pod "Branch-SDK", path: "../node_modules/react-native-branch/ios"

target "AwesomeProject"
project "AwesomeProject", "Test-Debug" => :debug, "Test-Release" => :release
